/*
 * CauchyMoveGenerator.h
 *
 *  Created on: 29 lip 2019
 *      Author: pkua
 */

#ifndef CAUCHYMOVEGENERATOR_H_
#define CAUCHYMOVEGENERATOR_H_

#include <random>
#include <cmath>
#include <curand_kernel.h>

#include "simulation/MoveGenerator.h"
#include "utils/CudaDefines.h"


/**
 * @brief A `__host__ __device__` class generating moves according to Cauchy distribution in radius and uniform
 * distribution in angle.
 */
class CauchyMoveGenerator : public MoveGenerator {
private:

#if CUDA_HOST_COMPILATION
    std::mt19937 randomGenerator;
    std::cauchy_distribution<float> cauchyDistribution;
    std::uniform_real_distribution<float> uniformAngleDistribution;
#else // CUDA_DEVICE_COMPILATION
    float width;
    curandState *states;
    size_t numberOfTrajectories;

    CUDA_DEV float randomCauchy();
#endif

public:

#if CUDA_HOST_COMPILATION
    /**
     * @brief `__host__` constructor, which initializes the generators using seeds generated by byte generator seeded
     * with @a seed parameter.
     *
     * @param width the width parameter in Cauchy distribution
     * @param integrationStep the integration step in the diffusion used to rescale the distribution properly - in this
     * case by square root of the integration step
     * @param seed the random seed for generators
     */
    CUDA_HOST CauchyMoveGenerator(float width, float integrationStep, unsigned int seed);

#else // CUDA_DEVICE_COMPILATION
    /**
     * @brief `__device__` constructor, which initializes the generators using seeds generated by byte generator seeded
     * with @a seed parameter.
     *
     * The constructor is expected to be called only by the first CUDA thread.
     *
     * @param width the width parameter in Cauchy distribution
     * @param integrationStep the integration step in the diffusion used to rescale the distribution properly - in this
     * case by square root of the integration step
     * @param seed the random seed for generators
     * @param numberOfTrajectories the number of trajectories for which independent number will be sampled on GPU
     */
    CUDA_DEV CauchyMoveGenerator(float width, float integrationStep, unsigned int seed, size_t numberOfTrajectories);

#endif

    CUDA_HOSTDEV CauchyMoveGenerator(const CauchyMoveGenerator &other) = delete;
    CUDA_HOSTDEV CauchyMoveGenerator operator=(CauchyMoveGenerator other) = delete;

    /**
     * @brief The destructor which is expected to be called only in the first CUDA thread. On CPU it does nothing.
     */
    CUDA_HOSTDEV ~CauchyMoveGenerator();

    /**
     * @brief Generates random move according to Cauchy distribution in radius and uniform distribution in angle.
     *
     * In GPU version, it respects the id of CUDA thread and for each thread the sequences are independent.
     *
     * @return random move according to Cauchy distribution in radius and uniform distribution in angle
     */
    CUDA_HOSTDEV Move generateMove() override;
};


#endif /* CAUCHYMOVEGENERATOR_H_ */

