/*
 * CPUCauchyMoveGenerator.h
 *
 *  Created on: 29 lip 2019
 *      Author: pkua
 */

#ifndef CPUCAUCHYMOVEGENERATOR_H_
#define CPUCAUCHYMOVEGENERATOR_H_

#include <random>
#include <cmath>

#include "random_walker/MoveGenerator.h"

/**
 * @brief Generates moves on CPU according to Cauchy distribution in radius and uniform distribution in angle.
 */
class CPUCauchyMoveGenerator : public MoveGenerator {
private:
    std::mt19937 randomGenerator;
    std::cauchy_distribution<float> cauchyDistribution;
    std::uniform_real_distribution<float> uniformAngleDistribution;

public:
    /**
     * @brief Initializes the generators using seeds generated by byte generator seeded with @a seed parameter
     *
     * @param width the width parameter in Cauchy distribution
     * @param seed the random seed for generators
     */
    CPUCauchyMoveGenerator(float width, unsigned int seed);

    /**
     * @brief Generates random move on CPU according to Cauchy distribution in radius and uniform distribution in angle.
     *
     * @return random move according to Cauchy distribution in radius and uniform distribution in angle
     */
    Move generateMove() override;
};

#endif /* CPUCAUCHYMOVEGENERATOR_H_ */
